name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn

      - name: Compile project
        run: yarn build

      - name: Release on npm
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get changelog
        id: changelog
        shell: bash
        # trick for multiline variables
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$(head -100 HISTORY.md)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Get version
        id: version
        run: echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Notify on Slack
        uses: bloodyowl/slack-message-release-action@v1.1.5
        with:
          version: ${{ steps.version.outputs.version }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
